Styles Quick Edit badge  to float right
LaunchCodeLiftoffProjects/moore-market pull request #22
Opened 2019-02-26 19:31 UTC by zstephenj

Styles the Quick Edit badge on each product to float right so they are all in alignment, despite varying price or quantity lengths.

2019-02-26 21:23 UTC, iktani approved these changes

2019-02-27 01:18 UTC, cecoppinger approved these changes

2019-02-27 20:09 UTC, ryuhhnn commented
I usually wouldn't mind, but I'm going to nitpick this one. I would refrain from using CSS `float` as it technically shouldn't be used as a layout mechanism. It's better to use flexbox. Also, never inline styles, always use classes :)

2019-02-27 20:10 UTC, ryanis-online requested changes

2019-02-27 20:10 UTC, ryuhhnn commented on frontend/src/components/Product/FarmerProductItem.vue
> +                <a @click='changeIsEditingPrice()' class='badge badge-success ml-3 mousePointer' style='float:right;'> Quick Edit </a>
Preferably change this to use flexbox, but at the very least, make this a class (psst: bootstrap has a built in class that does this already)

2019-03-01 19:04 UTC, ryanis-online approved these changes
Thanks for making those changes!

2019-03-01 19:04 UTC, merged