Cleaned up my pull request
LaunchCodeLiftoffProjects/moore-market pull request #4
Opened 2019-02-04 21:21 UTC by cecoppinger

I tried to get to most of your comments, Ryan.  On the last one you mentioned I'm looking into using environment variables.  For now I've got the connection string stored in the appsettings.json file.

2019-02-05 20:07 UTC, iktani approved these changes
works on my end. I'm approving it.

2019-02-05 20:21 UTC, ryanis-online requested changes
You still need to rebase this and get rid of the `.vs` directory and all the cached and compiled files

2019-02-06 02:58 UTC, simpson1986 approved these changes

2019-02-06 19:21 UTC, ryanis-online approved these changes
Very good job!!

2019-02-06 19:21 UTC, ryuhhnn commented on .gitignore
> +##We don't need all these I just copied and pasted a template that I found from googling - Clarence
Good thinking! These templates are sometimes better to use anyways since a lot of times it's easy to forget about these

2019-02-06 22:18 UTC, zstephenj approved these changes

2019-02-06 22:30 UTC, merged